// lib/constants.ts

export const CONGO_CITIES = [
  "Brazzaville",
  "Pointe-Noire",
  "Dolisie",
  "Nkayi",
  "Oyo",
  "Ouesso",
  "Owando",
  "Sibiti",
  "Madingou",
  "Gamboma",
  "Impfondo",
  "Djambala",
  "Ewo",
  "Makoua",
  "Boundji",
  "Okoyo",
  "Etoumbi",
  "Kéllé",
  "Ollombo",
  "Obouya",
  "Ngo",
  "Bouansa",
  "Loutété",
  "Loudima",
  "Mindouli",
  "Pokola",
  "Thanry",
  "Dongou",
  "Betou",
  "Enyelle",
  "Epere",
  "Cameroun (International)",
].sort(); // Trie par ordre alphabétique automatiquement
